---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: install.redhat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: install.debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: users.yml

# Nginx setup.
- import_tasks: vhosts.yml

- name: Copy nginx configuration in place.
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx is started and enabled to start at boot.
  service:
    name: nginx
    state: started
    enabled: true
